#!/usr/bin/env python3
"""Disk-patch UnquantizedEmbeddingMethod for embed_tokens_quant derivatives.

EngineCore-safe (edits site-packages). Loads int8 weight + scale from
/model/model-embed-int{N}.safetensors even if AutoWeightsLoader only maps .weight.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

MARKER = "EMBED_QUANT_VPE_PATCH_V2"

HELPER = r'''
# generated by patch_embed_int8.py
from __future__ import annotations
import json
from pathlib import Path
import torch
from safetensors import safe_open
from torch.nn.parameter import Parameter
from vllm.model_executor.utils import set_weight_attrs

def read_embed_quant_cfg():
    p = Path("/model/config.json")
    if not p.exists():
        return None
    try:
        eq = json.loads(p.read_text()).get("embed_tokens_quant")
    except Exception:
        return None
    if not eq:
        return None
    return {"bits": int(eq.get("bits", 8)), "packed": bool(eq.get("packed", False))}

def maybe_materialize_int8_embed(layer) -> bool:
    """If derivative config present, ensure layer.weight is int8 + weight_scale."""
    eq = read_embed_quant_cfg()
    if eq is None:
        return False
    bits = eq["bits"]
    packed = eq["packed"]
    embed_path = Path(f"/model/model-embed-int{bits}.safetensors")
    if not embed_path.exists():
        print(f"[embed-quant] missing {embed_path}", flush=True)
        return False
    key_w = "model.language_model.embed_tokens.weight"
    key_s = "model.language_model.embed_tokens.weight_scale"
    with safe_open(str(embed_path), framework="pt", device="cpu") as f:
        q = f.get_tensor(key_w)
        scale = f.get_tensor(key_s)
    # Move to layer device if weight already placed
    dev = layer.weight.device if hasattr(layer, "weight") else torch.device("cpu")
    q = q.to(device=dev)
    scale = scale.to(device=dev)
    layer._embed_quant_bits = bits
    layer._embed_quant_packed = packed
    layer.hidden_size = int(scale.shape and (q.shape[1] * (2 if packed else 1)))
    if packed:
        # packed cols = ceil(H/2); infer H from scale broadcast usage in forward
        layer.hidden_size = q.shape[1] * 2  # may be +1 pad; forward trims
    else:
        layer.hidden_size = q.shape[1]
    layer.weight = Parameter(q.contiguous(), requires_grad=False)
    layer.weight_scale = Parameter(scale.contiguous(), requires_grad=False)
    print(
        f"[embed-quant] materialized int{bits} embed {tuple(q.shape)} "
        f"on {dev} gib={q.numel()/1024**3:.3f}",
        flush=True,
    )
    return True

def int8_embedding(layer, input_):
    bits = getattr(layer, "_embed_quant_bits", 8)
    packed = getattr(layer, "_embed_quant_packed", False)
    scale = layer.weight_scale
    if scale.ndim == 1:
        scale = scale.unsqueeze(-1)
    if bits == 8 and not packed:
        return layer.weight[input_].to(torch.float16) * scale[input_]
    packed_rows = layer.weight[input_].view(torch.uint8)
    lo = (packed_rows & 0x0F).to(torch.int16)
    hi = ((packed_rows >> 4) & 0x0F).to(torch.int16)
    lo = torch.where(lo >= 8, lo - 16, lo)
    hi = torch.where(hi >= 8, hi - 16, hi)
    H = layer.hidden_size
    # if padded packed, hidden_size may be even; trim to scale-implied
    out = torch.empty(*input_.shape, packed_rows.shape[-1] * 2, dtype=torch.float16, device=input_.device)
    out[..., 0::2] = lo.to(torch.float16)
    out[..., 1::2] = hi.to(torch.float16)
    # trim to 5120 typically
    if out.shape[-1] > H:
        out = out[..., :H]
    return out * scale[input_]
'''


def patch_vpe(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        print(f"[embed-quant] already patched {path}")
        return

    # Patch process_weights_after_loading on UnquantizedEmbeddingMethod
    old_proc = '''    def process_weights_after_loading(self, layer: torch.nn.Module) -> None:
        if current_platform.is_cpu():
            from vllm.model_executor.layers.utils import dispatch_cpu_unquantized_gemm

            dispatch_cpu_unquantized_gemm(layer, remove_weight=False)'''

    new_proc = f'''    def process_weights_after_loading(self, layer: torch.nn.Module) -> None:
        # {MARKER}
        try:
            from vllm.model_executor.layers.quantization.embed_int8_runtime import (
                maybe_materialize_int8_embed,
            )
            if maybe_materialize_int8_embed(layer):
                return
        except Exception as _e:
            print(f"[embed-quant] materialize failed: {{_e}}", flush=True)
        if current_platform.is_cpu():
            from vllm.model_executor.layers.utils import dispatch_cpu_unquantized_gemm

            dispatch_cpu_unquantized_gemm(layer, remove_weight=False)'''

    if old_proc not in text:
        # flexible match
        m = re.search(
            r"    def process_weights_after_loading\(self, layer: torch\.nn\.Module\) -> None:\n"
            r"        if current_platform\.is_cpu\(\):",
            text,
        )
        if not m:
            raise RuntimeError(f"process_weights_after_loading not found in {path}")
        text = (
            text[: m.start()]
            + new_proc.replace(
                "        if current_platform.is_cpu():",
                "        if current_platform.is_cpu():",
            )
            # new_proc already includes cpu branch; need to skip original cpu block start
            # Actually we replaced only through is_cpu line — messy.
            # Use exact old_proc replacement only.
        )
        raise RuntimeError("exact process_weights block mismatch — abort")

    text = text.replace(old_proc, new_proc, 1)

    old_emb = '''    def embedding(self, layer: torch.nn.Module, input_: torch.Tensor) -> torch.Tensor:
        return F.embedding(input_, layer.weight)'''

    new_emb = f'''    def embedding(self, layer: torch.nn.Module, input_: torch.Tensor) -> torch.Tensor:
        # {MARKER}
        if hasattr(layer, "weight_scale") and layer.weight.dtype == torch.int8:
            from vllm.model_executor.layers.quantization.embed_int8_runtime import (
                int8_embedding,
            )
            return int8_embedding(layer, input_)
        return F.embedding(input_, layer.weight)'''

    if old_emb not in text:
        raise RuntimeError(f"embedding() not found in {path}")
    text = text.replace(old_emb, new_emb, 1)

    path.write_text(text, encoding="utf-8")
    print(f"[embed-quant] patched {path}")


def main() -> int:
    # Also strip weight_scale from index so AutoWeightsLoader doesn't require the param
    idx_path = Path("/model/model.safetensors.index.json")
    if idx_path.exists():
        try:
            idx = json.loads(idx_path.read_text())
            wm = idx.get("weight_map", {})
            if "model.language_model.embed_tokens.weight_scale" in wm:
                # index is ro mount — can't write. OK: we'll leave it; materialize replaces after load.
                # If loader errors before process_weights, we must remove scale from map in derivative on host.
                print("[embed-quant] NOTE: weight_scale still in index (host should strip)", flush=True)
        except Exception as e:
            print("[embed-quant] index check", e)

    roots = [
        Path("/opt/venv/lib/python3.12/site-packages/vllm"),
        Path("/workspace/vllm/vllm"),
    ]
    ok = False
    for root in roots:
        if not root.exists():
            continue
        qdir = root / "model_executor" / "layers" / "quantization"
        qdir.mkdir(parents=True, exist_ok=True)
        (qdir / "embed_int8_runtime.py").write_text(HELPER, encoding="utf-8")
        print(f"[embed-quant] wrote {qdir / 'embed_int8_runtime.py'}")
        vpe = root / "model_executor" / "layers" / "vocab_parallel_embedding.py"
        if vpe.exists():
            patch_vpe(vpe)
            ok = True
    if not ok:
        print("FAIL no vpe", file=sys.stderr)
        return 1
    print("[embed-quant] disk patch OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
